# -*- coding: utf-8 -*-
"""Road_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Azk-egDdTblh7tyHb81cd_ZH6i8QMd61
"""

import pandas as pd
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

data = pd.read_excel('/content/road data.xlsx')

X = data[['Time', 'sta', 'wether', 'week or weekend']]
y = data['number of vehicles']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42)


poly = PolynomialFeatures(degree=5, include_bias=False)
X_train_poly = poly.fit_transform(X_train)
X_test_poly = poly.transform(X_test)


model = LinearRegression()
model.fit(X_train_poly, y_train)

def filter_data(data):
  data[data<0]=0

  return data.astype(int)

"""**Testing train model**"""

y_pred = model.predict(X_test_poly)
print('predict data:'+
      str(filter_data(y_pred))
      )
print('real data:'+
      str(y_test.values)
      )

# coefficients = model.coef_
# intercept = model.intercept_

# print("Coefficients:", coefficients)
# print("Intercept:", intercept)

from sklearn.metrics import mean_squared_error, r2_score
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Mean Squared Error:", mse)
print("R^2 Score:", r2)

"""**Save Train Model**"""

import joblib

model_filename = 'polynomial_regression_model.pkl'
joblib.dump(model, model_filename)


poly_filename = 'polynomial_features.pkl'
joblib.dump(poly, poly_filename)

"""**Load Save model**"""

loaded_model = joblib.load('polynomial_regression_model.pkl')
loaded_poly = joblib.load('polynomial_features.pkl')

"""**New Data**"""

new_data = pd.DataFrame({
    'Time': [120],
    'sta': [1],
    'wether': [0],
    'week or weekend': [0]
})

"""**Predict for new Data**"""

new_data_poly = loaded_poly.transform(new_data)


predictions = loaded_model.predict(new_data_poly)


print("Predictions for new data:", filter_data(predictions)[0])